// Type: CommunityExpressNS.EResult
// Assembly: CommunityExpress, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
// MVID: 3B3F745C-AA2A-4DDF-AA8A-F5898AF84B8D
// Assembly location: F:\Program Files (x86)\FEZ\CommunityExpress.dll

namespace CommunityExpressNS
{
  public enum EResult
  {
    EResultOK = 1,
    EResultFail = 2,
    EResultNoConnection = 3,
    EResultInvalidPassword = 5,
    EResultLoggedInElsewhere = 6,
    EResultInvalidProtocolVer = 7,
    EResultInvalidParam = 8,
    EResultFileNotFound = 9,
    EResultBusy = 10,
    EResultInvalidState = 11,
    EResultInvalidName = 12,
    EResultInvalidEmail = 13,
    EResultDuplicateName = 14,
    EResultAccessDenied = 15,
    EResultTimeout = 16,
    EResultBanned = 17,
    EResultAccountNotFound = 18,
    EResultInvalidSteamID = 19,
    EResultServiceUnavailable = 20,
    EResultNotLoggedOn = 21,
    EResultPending = 22,
    EResultEncryptionFailure = 23,
    EResultInsufficientPrivilege = 24,
    EResultLimitExceeded = 25,
    EResultRevoked = 26,
    EResultExpired = 27,
    EResultAlreadyRedeemed = 28,
    EResultDuplicateRequest = 29,
    EResultAlreadyOwned = 30,
    EResultIPNotFound = 31,
    EResultPersistFailed = 32,
    EResultLockingFailed = 33,
    EResultLogonSessionReplaced = 34,
    EResultConnectFailed = 35,
    EResultHandshakeFailed = 36,
    EResultIOFailure = 37,
    EResultRemoteDisconnect = 38,
    EResultShoppingCartNotFound = 39,
    EResultBlocked = 40,
    EResultIgnored = 41,
    EResultNoMatch = 42,
    EResultAccountDisabled = 43,
    EResultServiceReadOnly = 44,
    EResultAccountNotFeatured = 45,
    EResultAdministratorOK = 46,
    EResultContentVersion = 47,
    EResultTryAnotherCM = 48,
    EResultPasswordRequiredToKickSession = 49,
    EResultAlreadyLoggedInElsewhere = 50,
    EResultSuspended = 51,
    EResultCancelled = 52,
    EResultDataCorruption = 53,
    EResultDiskFull = 54,
    EResultRemoteCallFailed = 55,
  }
}
