// Type: OpenTK.Audio.OpenAL.EfxEffectf
// Assembly: OpenTK, Version=1.1.0.0, Culture=neutral, PublicKeyToken=bad199fe84eb3df4
// MVID: FE2CFFE8-B942-430E-8C15-E783DB6F0AD6
// Assembly location: F:\Program Files (x86)\FEZ\OpenTK.dll

namespace OpenTK.Audio.OpenAL
{
  public enum EfxEffectf
  {
    AutowahAttackTime = 1,
    DistortionEdge = 1,
    EaxReverbDensity = 1,
    EchoDelay = 1,
    EqualizerLowGain = 1,
    FrequencyShifterFrequency = 1,
    ReverbDensity = 1,
    RingModulatorFrequency = 1,
    AutowahReleaseTime = 2,
    DistortionGain = 2,
    EaxReverbDiffusion = 2,
    EchoLRDelay = 2,
    EqualizerLowCutoff = 2,
    ReverbDiffusion = 2,
    RingModulatorHighpassCutoff = 2,
    AutowahResonance = 3,
    ChorusRate = 3,
    DistortionLowpassCutoff = 3,
    EaxReverbGain = 3,
    EchoDamping = 3,
    EqualizerMid1Gain = 3,
    FlangerRate = 3,
    ReverbGain = 3,
    AutowahPeakGain = 4,
    ChorusDepth = 4,
    DistortionEQCenter = 4,
    EaxReverbGainHF = 4,
    EchoFeedback = 4,
    EqualizerMid1Center = 4,
    FlangerDepth = 4,
    ReverbGainHF = 4,
    ChorusFeedback = 5,
    DistortionEQBandwidth = 5,
    EaxReverbGainLF = 5,
    EchoSpread = 5,
    EqualizerMid1Width = 5,
    FlangerFeedback = 5,
    ReverbDecayTime = 5,
    ChorusDelay = 6,
    EaxReverbDecayTime = 6,
    EqualizerMid2Gain = 6,
    FlangerDelay = 6,
    ReverbDecayHFRatio = 6,
    VocalMorpherRate = 6,
    EaxReverbDecayHFRatio = 7,
    EqualizerMid2Center = 7,
    ReverbReflectionsGain = 7,
    EaxReverbDecayLFRatio = 8,
    EqualizerMid2Width = 8,
    ReverbReflectionsDelay = 8,
    EaxReverbReflectionsGain = 9,
    EqualizerHighGain = 9,
    ReverbLateReverbGain = 9,
    EaxReverbReflectionsDelay = 10,
    EqualizerHighCutoff = 10,
    ReverbLateReverbDelay = 10,
    ReverbAirAbsorptionGainHF = 11,
    EaxReverbLateReverbGain = 12,
    ReverbRoomRolloffFactor = 12,
    EaxReverbLateReverbDelay = 13,
    EaxReverbEchoTime = 15,
    EaxReverbEchoDepth = 16,
    EaxReverbModulationTime = 17,
    EaxReverbModulationDepth = 18,
    EaxReverbAirAbsorptionGainHF = 19,
    EaxReverbHFReference = 20,
    EaxReverbLFReference = 21,
    EaxReverbRoomRolloffFactor = 22,
  }
}
