// Type: Microsoft.Xna.Framework.GamerServices.GamerPresenceMode
// Assembly: MonoGame.Framework, Version=3.0.1.0, Culture=neutral, PublicKeyToken=null
// MVID: 69677294-4E99-4B9C-B72B-CC2D8AA03B63
// Assembly location: F:\Program Files (x86)\FEZ\MonoGame.Framework.dll

namespace Microsoft.Xna.Framework.GamerServices
{
  public enum GamerPresenceMode
  {
    ArcadeMode,
    AtMenu,
    BattlingBoss,
    CampaignMode,
    ChallengeMode,
    ConfiguringSettings,
    CoOpLevel,
    CoOpStage,
    CornflowerBlue,
    CustomizingPlayer,
    DifficultyEasy,
    DifficultyExtreme,
    DifficultyHard,
    DifficultyMedium,
    EditingLevel,
    ExplorationMode,
    FoundSecret,
    FreePlay,
    GameOver,
    InCombat,
    InGameStore,
    Level,
    LocalCoOp,
    LocalVersus,
    LookingForGames,
    Losing,
    Multiplayer,
    NearlyFinished,
    None,
    OnARoll,
    OnlineCoOp,
    OnlineVersus,
    Outnumbered,
    Paused,
    PlayingMinigame,
    PlayingWithFriends,
    PracticeMode,
    PuzzleMode,
    ScenarioMode,
    Score,
    ScoreIsTied,
    SettingUpMatch,
    SinglePlayer,
    Stage,
    StartingGame,
    StoryMode,
    StuckOnAHardBit,
    SurvivalMode,
    TimeAttack,
    TryingForRecord,
    TutorialMode,
    VersusComputer,
    VersusScore,
    WaitingForPlayers,
    WaitingInLobby,
    WastingTime,
    WatchingCredits,
    WatchingCutscene,
    Winning,
    WonTheGame,
  }
}
